
# Create your custom here.


# custom message code for response
GET_DATA_SUCCESS_CODE = 'GET_DATA_SUCCESS_CODE'
UPDATE_DATA_SUCCESS_CODE = 'UPDATE_DATA_SUCCESS_CODE'
DELETE_DATA_SUCCESS_CODE = 'DELETE_DATA_SUCCESS_CODE'
CREATE_DATA_SUCCESS_CODE = 'CREATE_DATA_SUCCESS_CODE'
INPUT_DATA_IS_INVALID = 'INPUT_DATA_IS_INVALID'
DATA_NOT_FOUND_CODE = 'DATA_NOT_FOUND_CODE'
SERVER_ERROR_CODE = 'SERVER_ERROR_CODE'
PERMISSION_REQUIRED_CODE = 'PERMISSION_REQUIRED_CODE'
METHOD_NOT_ACCEPTABLE_CODE = 'METHOD_NOT_ACCEPTABLE_CODE'
BAD_REQUEST_CODE = 'BAD_REQUEST_CODE'
MISSING_HEADER_CODE = 'MISSING_HEADER_CODE'
UNAUTHORIZED_CODE = 'UNAUTHORIZED_CODE'

